server:
  port: 9100
spring:
  iotdb:
    username: root
    password: root
    ip: 114.96.121.87
    port: 6667
    maxSize: 100
  datasource:
    username: root
    password: Hw123456
    url: jdbc:mysql://123.249.101.90:3306/big_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    cc.shunfu.bigdata.model.mapper: DEBUG
